---
- name: ensure pyOpenSSL installed
  package:
    name: pyOpenSSL
    state: present

- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: /home/centos/ssl/{{ssl_server_name}}
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /home/centos/ssl/{{ssl_server_name}}/privkey.pem

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /home/centos/{{ssl_server_name}}.csr
    privatekey_path: /home/centos/ssl/{{ ssl_server_name }}/privkey.pem
    common_name: "{{ ssl_server_name }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /home/centos/ssl/{{ ssl_server_name }}/fullchain.pem
    privatekey_path: /home/centos/ssl/{{ ssl_server_name }}/privkey.pem
    csr_path: /home/centos/{{ ssl_server_name }}.csr
    provider: selfsigned

   
