---
  - block:  
    - name: sure cert dir exists
      file: 
        path: /etc/nginx/ssl/cert
        state: directory

    - name: sure key dir exists
      file: 
        path: /etc/nginx/ssl/key
        state: directory

    - name: copy conf file
      template:
        src: "{{role_path}}/templates/conf.j2"
        dest: "{{nginx_conf_location}}"

    - name: copy ssl certs
      copy:
        src: "{{ssl_cert_location}}"
        dest: "{{nginx_ssl_cert_location}}"
        remote_src: yes

    - name: copy ssl keys
      copy:
        src: "{{ssl_key_location}}"
        dest: "{{nginx_ssl_key_location}}"
        remote_src: yes
    - name: restart service
      systemd: 
        name: nginx
        state: restarted
        daemon_reload: yes

    - name: open firewallports
      firewalld:
        port: "{{nginx_listen_port}}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
    - name: restart service
      systemd: 
        name: firewalld
        state: restarted
        daemon_reload: yes
    become: yes
    become_user: root


...
